name: PR Build Check

on:
  pull_request:
    branches:
      - main
      - master  # Adjust based on your main branch name

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Needed to get full git history for versioning

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable  # Use the latest stable Go version

      - name: Get version and git hash
        run: |
          echo "VERSION=$(git describe --tags --always --dirty)" >> $GITHUB_ENV
          echo "GIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build binary
        run: |
          cd API_gateway/proxy
          go build -ldflags "-X main.version=${VERSION} -X main.gitHash=${GIT_HASH}" -o api-gateway

      - name: Verify build success
        run: |
          if [ ! -f API_gateway/proxy/api-gateway ]; then
            echo "Build failed: api-gateway binary not found"
            exit 1
          fi
          echo "Build successful"