name: Build and Release All

on:
  release:
    types: [published]

jobs:
  build:
    name: Build for ${{ matrix.ubuntu_version }}
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - ubuntu_version: 20_04
            runner: ubuntu-20.04
            output_name: api-gateway-20-04
          - ubuntu_version: 22_04
            runner: ubuntu-22.04
            output_name: api-gateway-22-04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Get version and git hash
        run: |
          echo "VERSION=$(git describe --tags --always --dirty)" >> $GITHUB_ENV
          echo "GIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build binary for Ubuntu ${{ matrix.ubuntu_version }}
        run: |
          cd API_gateway/proxy
          go build -ldflags "-X main.version=${VERSION} -X main.gitHash=${GIT_HASH}" -o ${{ matrix.output_name }}

      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          files: API_gateway/proxy/${{ matrix.output_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
